# Generated by Django 6.0.2 on 2026-08-03 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehiculo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermisoCirculacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipalidad', models.CharField(max_length=100)),
                ('fecha_emision', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('archivo', models.FileField(upload_to='permisos_circulacion/')),
                ('observacion', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='permisos_circulacion', to='vehiculo.vehiculo')),
            ],
            options={
                'db_table': 'permisos_circulacion',
                'ordering': ['-fecha_vencimiento'],
            },
        ),
    ]
