# Generated by Django 6.0.2 on 2026-08-10 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehiculo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mantencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_revision_tecnica', models.DateField(blank=True, null=True)),
                ('fecha_gases', models.DateField(blank=True, null=True)),
                ('kilometraje', models.IntegerField(blank=True, null=True)),
                ('fecha_cambio_aceite', models.DateField(blank=True, null=True)),
                ('kilometraje_cambio_aceite', models.IntegerField(blank=True, null=True)),
                ('lugar_mantencion', models.CharField(max_length=150)),
                ('observacion', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mantenciones', to='vehiculo.vehiculo')),
            ],
            options={
                'db_table': 'mantenciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
