# Generated by Django 6.0.2 on 2026-08-10 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mantencion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mantencion',
            options={},
        ),
        migrations.RemoveField(
            model_name='mantencion',
            name='fecha_cambio_aceite',
        ),
        migrations.RemoveField(
            model_name='mantencion',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='mantencion',
            name='lugar_mantencion',
        ),
    ]
