# Generated by Django 6.0.2 on 2026-08-10 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantencion', '0002_alter_mantencion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantencion',
            name='archivo_gases',
            field=models.FileField(blank=True, null=True, upload_to='mantenciones/gases/'),
        ),
        migrations.AddField(
            model_name='mantencion',
            name='archivo_revision_tecnica',
            field=models.FileField(blank=True, null=True, upload_to='mantenciones/revision_tecnica/'),
        ),
    ]
