# Generated by Django 6.0.2 on 2026-08-14 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantencion', '0003_mantencion_archivo_gases_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramDestinatario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('chat_id', models.CharField(max_length=50, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
