# Generated by Django 6.0.2 on 2026-08-14 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantencion', '0004_telegramdestinatario'),
        ('vehiculo', '0003_remove_vehiculo_municipalidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramAvisoAceite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_aviso', models.CharField(max_length=20)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiculo.vehiculo')),
            ],
            options={
                'unique_together': {('vehiculo', 'tipo_aviso')},
            },
        ),
    ]
