# Generated by Django 6.0.2 on 2026-09-21 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantencion', '0005_telegramavisoaceite'),
        ('vehiculo', '0006_remove_vehiculo_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramAvisoRevisionTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_revision_tecnica', models.DateField()),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiculo.vehiculo')),
            ],
            options={
                'unique_together': {('vehiculo', 'fecha_revision_tecnica')},
            },
        ),
    ]
