# Generated by Django 6.0.2 on 2026-06-30 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleado', '0003_empleado_activo_empleado_fecha_creacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('CI', 'Carnet de Identidad'), ('LIC', 'Licencia de Conducir'), ('HIST', 'Hoja del Conductor')], max_length=10)),
                ('archivo', models.FileField(upload_to='documentos/')),
                ('fecha_emision', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='empleado.empleado')),
            ],
            options={
                'db_table': 'documentos',
            },
        ),
    ]
