# Generated by Django 6.0.2 on 2026-07-14 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos_empleados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='archivo_reverso',
            field=models.FileField(blank=True, null=True, upload_to='documentos/'),
        ),
    ]
