# Generated by Django 6.0.2 on 2026-08-24 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehiculo', '0004_vehiculo_tipo_vehiculo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seguro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(choices=[('BCI', 'Banco BCI')], default='BCI', max_length=50)),
                ('numero_poliza', models.CharField(max_length=100)),
                ('tipo_vehiculo', models.CharField(choices=[('CAMIONETA', 'CAMIONETA'), ('CAMION_LIVIANO', 'CAMIÓN LIVIANO'), ('CAMION', 'CAMION'), ('TODO_TERRENO', 'TODO TERRENO'), ('FURGON', 'FURGON')], max_length=30)),
                ('marca', models.CharField(choices=[('HYUNDAI', 'HYUNDAI'), ('MITSUBISHI', 'MITSUBISHI'), ('CHEVROLET', 'CHEVROLET'), ('MITSUBISHI_FUSO', 'MITSUBISHI FUSO'), ('CITROEN', 'CITROEN'), ('NISSAN', 'NISSAN'), ('JAC', 'JAC')], max_length=50)),
                ('modelo', models.CharField(choices=[('PORTER', 'PORTER'), ('HD32', 'HD32'), ('CARTER 413', 'CARTER 413'), ('FVR 1724', 'FVR 1724'), ('NPR 612', 'NPR 612'), ('BERLINGO', 'BERLINGO'), ('HD35', 'HD35'), ('KICKS', 'KICKS'), ('URBAN', 'URBAN')], max_length=50)),
                ('año', models.PositiveIntegerField()),
                ('fecha_vencimiento', models.DateField()),
                ('archivo', models.FileField(blank=True, null=True, upload_to='seguros/')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguros', to='vehiculo.vehiculo')),
            ],
        ),
    ]
