# Generated by Django 6.0.2 on 2026-08-25 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seguros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seguro',
            name='año',
        ),
        migrations.RemoveField(
            model_name='seguro',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='seguro',
            name='modelo',
        ),
        migrations.RemoveField(
            model_name='seguro',
            name='tipo_vehiculo',
        ),
    ]
