# Generated by Django 6.0.2 on 2026-08-25 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguros', '0002_remove_seguro_año_remove_seguro_marca_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seguro',
            name='item',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
