# Generated by Django 6.0.2 on 2026-09-01 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguros', '0003_seguro_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguro',
            name='item',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
