# Generated by Django 6.0.2 on 2026-09-01 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguros', '0004_alter_seguro_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguro',
            name='banco',
            field=models.CharField(choices=[('BCI', 'Banco BCI'), ('SURA', 'SURA')], default='BCI', max_length=50),
        ),
    ]
