# Generated by Django 6.0.2 on 2026-06-15 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bencina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('rut', models.CharField(max_length=15)),
                ('vehiculo', models.CharField(max_length=100)),
                ('monto', models.PositiveIntegerField()),
                ('kilometraje', models.PositiveIntegerField()),
                ('recibo', models.ImageField(upload_to='recibos/')),
                ('fecha_creacion', models.DateTimeField()),
            ],
            options={
                'db_table': 'bencina',
                'managed': False,
            },
        ),
    ]
