# Generated by Django 6.0.2 on 2026-06-25 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bencina', '0001_initial'),
        ('empleado', '0003_empleado_activo_empleado_fecha_creacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlTarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('hora_checkin', models.TimeField()),
                ('hora_checkout', models.TimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='controles_tarjeta', to='empleado.empleado')),
            ],
            options={
                'db_table': 'control_tarjeta',
            },
        ),
    ]
