# Generated by Django 6.0.2 on 2026-07-02 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bencina', '0002_controltarjeta'),
        ('vehiculo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='controltarjeta',
            name='vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='vehiculo.vehiculo'),
        ),
    ]
