# Generated by Django 6.0.2 on 2026-07-06 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bencina', '0003_controltarjeta_vehiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='controltarjeta',
            name='fecha_editable',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
