# Generated by Django 6.0.2 on 2026-07-08 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bencina', '0004_controltarjeta_fecha_editable'),
    ]

    operations = [
        migrations.AddField(
            model_name='controltarjeta',
            name='fecha_hasta',
            field=models.DateField(blank=True, null=True),
        ),
    ]
