# Generated by Django 6.0.2 on 2026-07-24 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bencina', '0005_controltarjeta_fecha_hasta'),
    ]

    operations = [
        migrations.AddField(
            model_name='controltarjeta',
            name='uso_tarjeta',
            field=models.CharField(blank=True, choices=[('SI', 'Utilizada'), ('NO', 'No utilizada')], max_length=2, null=True),
        ),
    ]
