# Generated by Django 6.0.2 on 2026-07-24 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bencina', '0006_controltarjeta_uso_tarjeta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controltarjeta',
            name='uso_tarjeta',
            field=models.BooleanField(default=True),
        ),
    ]
