# Generated by Django 6.0.2 on 2026-08-12 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='lugar_mantencion',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='municipalidad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='propietario',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
