# Generated by Django 6.0.2 on 2026-08-13 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0002_vehiculo_lugar_mantencion_vehiculo_municipalidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='municipalidad',
        ),
    ]
