# Generated by Django 6.0.2 on 2026-08-24 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0003_remove_vehiculo_municipalidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='tipo_vehiculo',
            field=models.CharField(blank=True, choices=[('CAMIONETA', 'CAMIONETA'), ('CAMION_LIVIANO', 'CAMIÓN LIVIANO'), ('CAMION', 'CAMION'), ('TODO_TERRENO', 'TODO TERRENO'), ('FURGON', 'FURGON')], max_length=30, null=True),
        ),
    ]
