# Generated by Django 6.0.2 on 2026-08-25 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0005_vehiculo_anio_vehiculo_n_motor_vehiculo_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='tipo',
        ),
    ]
