# Generated by Django 6.0.2 on 2026-06-15 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleado',
            options={},
        ),
        migrations.AlterModelTable(
            name='empleado',
            table='empleados',
        ),
    ]
