# Generated by Django 6.0.2 on 2026-07-21 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0004_alter_empleado_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='bodega',
            field=models.CharField(blank=True, choices=[('BODEGA 1', 'BODEGA 1'), ('BODEGA 2', 'BODEGA 2'), ('BODEGA 3', 'BODEGA 3'), ('BODEGA 4', 'BODEGA 4')], max_length=50, null=True),
        ),
    ]
