# Generated by Django 6.0.2 on 2026-07-21 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0005_empleado_bodega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='bodega',
            field=models.CharField(blank=True, choices=[('ALDUNATE', 'ALDUNATE'), ('VIEL', 'VIEL'), ('SAN FRANCISCO', 'SAN FRANCISCO')], max_length=50, null=True),
        ),
    ]
