# Generated by Django 6.0.2 on 2026-07-22 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0006_alter_empleado_bodega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='cargo',
            field=models.CharField(choices=[('JEFE BODEGA', 'JEFE BODEGA'), ('SUB ENCARGADO BODEGA', 'SUB ENCARGADO BODEGA'), ('GESTOR DE FLOTA', 'GESTOR DE FLOTA'), ('OPERADOR GRUA HORQUILLA', 'OPERADOR GRUA HORQUILLA'), ('OPERADOR CORTE', 'OPERADOR CORTE'), ('EMPAQUE', 'EMPAQUE'), ('CHOFER', 'CHOFER'), ('PEONETA', 'PEONETA'), ('APILADOR', 'APILADOR')], max_length=50),
        ),
    ]
